// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const interSemibold = Inter({
  variable: "--font-inter-semibold",
  subsets: ["latin"],
  weight: "600",
});

const interMedium = Inter({
  variable: "--font-inter-medium",
  subsets: ["latin"],
  weight: "500",
});

const interLight = Inter({
  variable: "--font-inter-light",
  subsets: ["latin"],
  weight: "300",
});

export const metadata: Metadata = {
  title: "Criado com a Lasy",
  description: "Projeto criado com Lasy AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${interSemibold.variable} ${interMedium.variable} ${interLight.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
